---
abstract: 'AnyEvent crontab with DateTime::Event::Cron'
author:
  - 'Clinton Gormley <drtech@traveljury.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-DateTime-Cron
provides:
  AnyEvent::DateTime::Cron:
    file: lib/AnyEvent/DateTime/Cron.pm
    version: 0.01
requires:
  AnyEvent: 0
  DateTime: 0
  DateTime::Event::Cron: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
